UmizuVatten/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.main, name='main'),
    path('result', views.res, name = 'results'),
    path('form/', views.userForm, name='userForm')

]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms

jenis_kelamin_choices =[
    ('Laki-laki', 'Male'),
    ('Perempuan', 'Female')
]

air_penting_choices = [
    (0.25,1),
    (0.5,2),
    (0.75,3),
    (1,4)
]

air_dekat = [
    (1, "Yes"),
    (0,"No"),
]

camilan_choices = [
    (0.25, "Maximum once a week"),
    (0.5, "2-4 times a week"),
    (0.75, "5-6 times a week"),
    (1, "Every day")
]

air_choices = [
    (0.25, "0-1 glass per day"),
    (0.5, "2-4 glasses per day"),
    (0.75, "5-7 glasses per day"),
    (1, ">= 8 glasses per day")
]



class UserForm(forms.Form):
    nama = forms.CharField(
        max_length=200,
        widget=forms.TextInput(
            attrs={
                'class': 'text-input',
                'placeholder': 'type your name',
            }
        )
    )

    umur = forms.IntegerField(
        widget=forms.NumberInput(
             attrs={
                'class': 'text-input',
                'placeholder': 'type your age',
            }
        )
    )

    jenis_kelamin = forms.ChoiceField(
        widget=forms.RadioSelect(
           attrs={
               'class': 'rad-but',
           }
        ),
        choices=jenis_kelamin_choices,
    )

    air_penting = forms.ChoiceField(
        widget=forms.RadioSelect(
            attrs={
               'class': 'rad-but',
               'id': 'inl',
           }
        ),
        choices=air_penting_choices,
    )

    air_dekat = forms.ChoiceField(
        widget=forms.RadioSelect(
            attrs={
               'class': 'rad-but',
           }
        ),
        choices=air_dekat,
    )

    camilan = forms.ChoiceField(
        widget=forms.RadioSelect(
            attrs={
               'class': 'rad-but',
           }
        ),
        choices=camilan_choices,
    )

    air = forms.ChoiceField(
        widget=forms.RadioSelect(
            attrs={
               'class': 'rad-but',
           }
        ),
        choices= air_choices,
    )

main/views.py
from django.shortcuts import render
from .forms import UserForm
from .ai import *

# Create your views here.
def main(request):
    return render(request, 'main.html')

def res(request):
    category = 0.75
    template = "category_{}.html".format(category)
    return render(request, template)

def userForm(request):
    if request.method == "POST":
        # get the field from form
        air_penting = float(request.POST.get('air_penting'))
        air_dekat = float(request.POST.get('air_dekat'))
        camilan = float(request.POST.get('camilan'))

        # Store the input in list
        input_pengguna = list()
        input_pengguna.append(air_penting)
        input_pengguna.append(air_dekat)
        input_pengguna.append(camilan)
        
        # Call the ai
        filename = 'use.csv'
        dataset = load_csv(filename)
        summaries = summarize_by_class(dataset)
        hasil = predict(summaries, input_pengguna)

        template = "category_{}.html".format(hasil)
        args = {
            'hasil': hasil,
        }
        return render(request, template , args)
    
    form = UserForm()
    args = {
        'form': form
    }
    return render(request, 'form.html', args)

main/templates/category_0.25.html
{% extends 'result.html' %}

{% block category %} Very Inconsistent {% endblock %}

{% block desc %}
    Lack of drinking water can cause lose focus, dehydration, and even other diseases.
    Make sure you drink at least 2L of water per day to stay hydrated!
{% endblock %}

main/templates/category_0.5.html
{% extends 'result.html' %}

{% block category %} Inconsistent {% endblock %}

{% block desc %}
    Consistently drinking enough water every day can help you not to lose focus, stay hydrated, and avoid various diseases.
    Make sure you drink at least 2L of water per day to stay hydrated!
{% endblock %}

main/templates/category_0.75.html
{% extends 'result.html' %}

{% block category %} consistent {% endblock %}

{% block desc %}
    You are consistently drinking enough water every day, but it still needs improvement!
    Consistently drinking enough water every day can help you not to lose focus, stay hydrated, and avoid various diseases.
    Make sure you drink at least 2L of water per day to stay hydrated!
{% endblock %}

main/templates/category_1.html
{% extends 'result.html' %}

{% block category %} Very Consistent {% endblock %}

{% block desc %}
    Nice! You're already very consistent in drinking enough water everyday.
    Don't forget to keep it up so you don't lose your focus, stay hydrated, and safe from all sorts of diseases.
{% endblock %}

main/templates/form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Form</title>
{% endblock %}

{% block link %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/form-style.css' %}">
{% endblock %}

{% block content %}
    <form action="{% url 'main:userForm' %}"  method="POST">
        {% csrf_token %}

        <div class="form-page" id="nama">
            <div class="progress">
                <h3>
                    <strong>1</strong> of 7
                </h3>
                <a href="#umur">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                </a>
            </div>
            <div class="question">
                <h2>What is your name?</h2>
                <div class="field">
                    {{ form.nama }}
                </div>
            </div>
        </div>


        <div class="form-page" id="umur">
            <div class="progress">
                <a href="#nama">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left"><polyline points="15 18 9 12 15 6"></polyline></svg>
                </a>
                <h3>
                    <strong>2</strong> of 7
                </h3> 
                <a href="#jenis_kelamin">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>

                </a>
            </div>
            <div class="question">
                <h2>How old are you?</h2>
                <div class="field">
                    {{ form.umur }}
                </div>
            </div>
        </div>



        <div class="form-page" id="jenis_kelamin">
            <div class="progress">
                <a href="#umur">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left"><polyline points="15 18 9 12 15 6"></polyline></svg>
                </a>
                <h3>
                    <strong>3</strong> of 7
                </h3>
                <a href="#sibuk">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>

                </a>
            </div>
            <div class="question">
                <h2>What is your gender?</h2>
                <div class="field">
                    {{ form.jenis_kelamin }}
                </div>
            </div>
        </div>


        <div class="form-page" id="sibuk">
            <div class="progress">
                <a href="#jenis_kelamin">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left"><polyline points="15 18 9 12 15 6"></polyline></svg>
                </a>
                <h3>
                    <strong>4</strong> of 7
                </h3>
                <a href="#sarapan">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>

                </a>
            </div>
            <div class="question">
                <h2>How important do you think it is to drink water?</h2>
                
                <div class="field">
                    <p>not important</p>
                    {{ form.air_penting }}
                    <p>very important</p>
                </div>
                
            </div>
        </div>



        <div class="form-page" id="sarapan">
            <div class="progress">
                <a href="#sibuk">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left"><polyline points="15 18 9 12 15 6"></polyline></svg>
                </a>
                <h3>
                    <strong>5</strong> of 7
                </h3>
                <a href="#jam_tidur">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>

                </a>
            </div>
            <div class="question">
                <h2>
                    Do you always have water near you?
                </h2>
                <div class="field">
                    {{ form.air_dekat }}
                </div>
            </div>
        </div>


        <div class="form-page" id="jam_tidur">
            <div class="progress">
                <a href="#sarapan">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left"><polyline points="15 18 9 12 15 6"></polyline></svg>
                </a>
                <h3>
                    <strong>6</strong> of 7
                </h3>
                <a href="#air">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>

                </a>
            </div>
            <div class="question">
                <h2>
                    In a week, how often do you snack?
                </h2>
                <div class="field">
                    {{ form.camilan }}
                </div>
            </div>
        </div>



        <div class="form-page" id="air">
            <div class="progress">
                <a href="#jam_tidur">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left"><polyline points="15 18 9 12 15 6"></polyline></svg>
                </a>
                <h3>
                    <strong>7</strong> of 7
                </h3>
            </div>
            <div class="question">
                <h2>
                    How many glass/es of water do you drink in a day?
                </h2>
                <div class="field">
                    {{ form.air }}
                </div>
            </div>
            <a href="{% url 'main:userForm' %}"><button type="submit">Submit</button></a>
        </div>



    </form>
{% endblock %}

main/templates/header.html
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand mb-0 h1" href="/">
        <div class="light blue2 inline">
            umizu
        </div>
        <div class="semi-bold">
            vatten
        </div>
    </a>
</nav>

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/homepage.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous">
{% endblock %}
        
{% block title %}
    <title>Umizu Vatten</title>
{% endblock %}

{% block content %}
    {% include 'header.html' %}
    <div class="content">
        <div class="title semi-bold">
            have you drink?
        </div>
        <div class="paragraph black">
            Drinking enough water consistently is the
            <br>
            beginning of good habits in daily life.
            <br>
            Let's find out how consistently you drink enough
            <br>
            water every day!
        </div>
        <br>
        <form action="{% url 'main:userForm' %}">
            <input class="btn btn-primary semi-bold" type="submit" value="start the test!"/>
        </form>
    </div>
{% endblock %}

main/templates/result.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title> Result </title>
{% endblock %}

{% block link %}
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Reenie+Beanie&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Mulish&display=swap">
    <link rel="stylesheet" href="{% static 'css/result.css' %}">
{% endblock %}

{% block content %}
    <div class="page-con">
        <div class="nav">
            <p> umizu<b>vatten </b> </p>
        </div>
    
        <div class="content-con">
            <div class="title-con">
                <p> Consistency Prediction Result </p>
            </div>
    
            <div class="desc-con">
                
                <div class="category">
                    <p> {% block category %}{% endblock %} </p>
                </div>
    
                <div class="desc">
                    <p>
                        {% block desc %}{% endblock %}
                    </p>
                </div>
                
                <div class="foot-desc">
                    <img src="{% static 'img/motivation.svg' %}" alt="motivation">

                    <p class='panascotta'>
                        panascotta
                    </p>
                </div>
            </div>
            

        </div>
    </div>
{% endblock %}

main/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for i in hasil %}
        <p>{{ i }}</p>
    {% endfor %}
</body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <link rel="icon" type="image/png" href="/static/img/favicon.png"/>
        {% block link %}{% endblock %}
        {% block title %}{% endblock %}
    </head>

    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>